#!/usr/bin/with-contenv bash

# create folders
if [ ! -d "${PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR}" ]; then \
mkdir -p "${PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR}"
chown -R media:media /config
fi

# check Library permissions
PUID=${PUID:-1001}
if [ ! "$(stat -c %u /config/Library)" = "$PUID" ]; then
	echo "Change in ownership detected, please be patient while we chown existing files"
	echo "This could take some time"
	chown media:media -R \
	/config/Library
fi

# permissions (non-recursive) on config root and folders
chown -R media:media \
	/config \
	/config/*
